### ISSUE TITLE
Can delete users table

### ISSUE THREAD

**Issue by dovilabs** [takumade/chazos#16]
Hi i just pulled your latest changes but sadly i can no longer delete user collection

**Comment by takumade** [comment]
I did it so that you cannot get locked out of the system after you delete user table

**Comment by dovilabs** [comment]
What if wanted full control

**Comment by takumade** [comment]
Some functionalities are place there for a reason

They are put in place for your own good.

**Comment by takumade** [comment]
I also assume that the end user is not tech savvy

**Comment by takumade** [comment]
I will add it in the future under settings,

**Comment by dovilabs** [comment]
That would be great

**Comment by takumade** [comment]
Also the project is still under construction

**Comment by dovilabs** [comment]
Ok thanks

**Comment by takumade** [comment]
I will close this

**Comment by dovilabs** [comment]
ok
